### ISSUE TITLE
Cannot fin module on Windows

### ISSUE THREAD

**Issue by Zarloc** [alexkirsz/catalyst-proxy#1]
On start error:

> catalyst start -h
> 
> ```
> module.js:340
>    throw err;
>           ^
> Error: Cannot find module '../../multisource-stream'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> ($npm_folder\node_modules\catalyst-proxy\lib\request.js:13:15)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
> ```

Changing "Multisource = require '../../multisource-stream'" to "Multisource = require 'multisource-stream'" in src/request.coffee solve error.

**Comment by alexkirsz** [comment]
Fixed by 0d619c5194ace6944632c13dcc76b2d4d054a4bd. Use `$ npm update -g catalyst-proxy` to update.

**Comment by alexkirsz** [comment]
I also updated the `multisource-stream` dependency in `0.1.2`. If you updated before, you should run the command once again.
